### ISSUE TITLE
Build mashlib gh-pages dist automatically

### ISSUE THREAD

**Issue by michielbdejong** [solid/mashlib#105]
The headers from https://solid.github.io/mashlib/dist/mashlib.js show `last-modified: Wed, 27 Nov 2019 14:16:36 GMT` 

We should have it build automatically

**Comment by RubenVerborgh** [comment]
Yes, this commit broke it: https://github.com/solid/mashlib/commit/d296a4476b1e912abb6603e1e9254800be8fc77e#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

Let me fix.
