### ISSUE TITLE
Task editor cannot show properly

### ISSUE THREAD

**Issue by hsinpeng** [solid/mashlib#152]
I just clone and run the latest mashlib ten minutes ago.
The task editor of todo list function doesn't work well on my chrome browser.
It works fine before, I use it almost every day for testing myself hosted CSS.
So I think it is a minor bug of the latest source code. F.Y.I.

**Comment by theRealImy** [comment]
@hsinpeng can you please detail your problem: console logs, screenshots...What does it mean 'doesn't work well'.
Thank you for reporting.

**Comment by bourgeoa** [comment]
Could you be more precise :
- mashlib version from npm or main branch
- detail on the problem with eventually screenshot

**Comment by hsinpeng** [comment]
Usually I use the following commands to run mashlib.
git clone https://github.com/solid/mashlib.git
cd mashlib
npm ci
npm run build
npx http-server ./dist

Then I use chrome to link http://localhost:8080/browse.html and enjoy its functionalities.
I am a solid newbie, so I like to clone the latest CSS and mashlib once couple weeks for trying new features.
Everything works fine before. But something wrong with task editor this time.
I will upload the screenshot ASAP.

**Comment by hsinpeng** [comment]
Hi contributors.
I tried tha same experience on linux ubuntu today.
The transparent edit window (only "X" close button visible) happens on the latest mashlib.
And everythings works fine with slightly old version. F.Y.I.

**Comment by timbl** [comment]
"But something wrong with task editor this time." .. if you click on the pencil (i the Task tab) or the title (in the Table view)then nothing happens?

**Comment by hsinpeng** [comment]
@timbl Yes, that's what happened. I guess that the Task tab does pop-up, but not invisible (only "X" close button visible).

**Comment by theRealImy** [comment]
Fixed on mashlib 1.8.1 on testserver now (and in main branch)

**Comment by hsinpeng** [comment]
Checked. It is fixed already. Thanks.

**Comment by theRealImy** [comment]
Thank you for checking @hsinpeng and thanks for making a ticket in the first place.
