### ISSUE TITLE
gh-pages hosted app not working

### ISSUE THREAD

**Issue by michielbdejong** [solid/mashlib#30]
https://github.com/solid/mashlib/blob/master/dist/databrowser.html#L4 should refer to https://solid.github.io/mashlib/dist/mashlib.min.js instead.

**Comment by Vinnl** [comment]
I think this issue will be redundant once https://github.com/solid/mashlib/pull/27 gets merged?

**Comment by michielbdejong** [comment]
I now see it's http://solid.github.io/mashlib/dist/ but that refers to 
```html
<script type="text/javascript" src="/mashlib.min.js"></script>
```
instead of
```html
<script type="text/javascript" src="./mashlib.min.js"></script>
```

**Comment by megoth** [comment]
I think this issue is resolved now? I'll close this issue, but please reopen it if it's still an issue.
