### ISSUE TITLE
Data browser web app has vanished

### ISSUE THREAD

**Issue by timbl** [solid/mashlib#57]
https://solid.github.io/mashlib/dist/browse.html
used to be an online version of the databrowser,
which is quite handy for inspecting remote data. 
Like many RDF viewers on the web.

It has been removed in that dist is cleaned by out NPM run clean I suspect.

**Comment by mikeadams1** [comment]
Great app!
I think it is here: https://github.com/solid/form-playground/browse.html
I use it here: https://index.solid.community/public/8-2/test4.html
The version of mashlib I am using is here: https://mikeadams1.github.io/form-playground/mashlib.js
Hope that helps.

**Comment by mikeadams1** [comment]
I filed an issue for it here. https://github.com/solid/form-playground/issues/6

**Comment by megoth** [comment]
@mikeadams1 you might wanna check out unpkg.com for referencing to specific versions of JS and CSS files you need, e.g. https://unpkg.com/solid-panes@1.3.15/style/tabbedtab.css

**Comment by timbl** [comment]
Here is a list from git of all the files in mashlib/dist which have been deleted. 
```
 delete mode 100644 dist/browse.html
 delete mode 100644 dist/databrowser.html
 delete mode 100644 dist/mash.css
 
 delete mode 100644 dist/mashlib-prealpha.js.map
 delete mode 100644 dist/es5.js
 delete mode 100644 dist/es5a.js
 delete mode 100644 dist/mashlib-es2015.js
 delete mode 100644 dist/mashlib-prealpha.js
 delete mode 100644 dist/mashlib-prealpha.js.map
 delete mode 100644 dist/mashlib.min.js
 delete mode 100644 dist/mashup-node-2.js
```
Not saying we should restore all of them.

**Comment by Vinnl** [comment]
@timbl The reason they got deleted (in PR #27) was that they were in the `dist/` directory, and thus appeared to be build artifacts. I've now moved them to the `gh-pages` directory in #61, which will get copied to `dist` on deployment to GitHub Pages to make sure the URLs are the same as before.

`mashlib.js`, `mashlib.min.js`, `mash.css` and the corresponding `.map` files were still being published, as far as I can see. (But be aware: they will be updated whenever their source files in `master` are updated, so anyone else depending on them is risking breaking changes, just as is the case for depending on any random CSS file online.)

Is there anything else you're still missing?

**Comment by mikeadams1** [comment]
@Vinnl https://solid.github.io/mashlib/dist/browse.html is still broken and only calls a mirror of the site to the data browser window. I am not sure if this is how it was meant to work but, I was able to get that working here: https://mikeadams1.github.io/browse/index.html

**Comment by Vinnl** [comment]
Hmm, my PR hasn't been merged yet, so it hasn't influenced what's at that URL. I'm not quite sure what it's supposed to do either, but since @timbl restored it, I suppose it's doing what he means it to do?

Is your thing working again? Glad to hear that if so :)

**Comment by mikeadams1** [comment]
Yes, it is working just fine, I can view any solid pod with it.

**Comment by mikeadams1** [comment]
I do want to say that it would not be possible without the mashlib.js file from @timbl, it is his, I got it here: https://timbl.com/timbl/Automation/Library/Mashup/mashlib.js
