### ISSUE TITLE
The warning about using `require('mashlib')` should only be given if it is used

### ISSUE THREAD

**Issue by timbl** [solid/mashlib#65]
The warning

Console.warn("Warning: mashlib's custom implementation of `require` will be deprecated in the future. Please import mashlib using a build-time bundler, or access the global `panes` variable when including it as a script."); //  Allow require('mashlib')

would be given (a few lined further down) when the function is *used*, so it goes when you stop using it.

**Comment by Vinnl** [comment]
Oops, that was certainly the intention, sorry - I'll fix it in a bit.

**Comment by Vinnl** [comment]
Fixed in 49c16b66728220861504b149cb76a92d9a1699c8.

(I presumed it to be uncontroversial enough not to need a pull request.)
