### ISSUE TITLE
Some default styles are missing from mash.css

### ISSUE THREAD

**Issue by megoth** [solid/mashlib#66]
In one of the newer iterations we introduced [reset.css](https://meyerweb.com/eric/tools/css/reset/) which strips a lot of default styles. This might've been a bit too much, as headers now look like any other text.

I suggest we either:

1) Remove the use of reset.css altogether, or a subset of the styles we do not want to use, or
2) Apply some styles we want to have as a common baseline, at least for headers

We might also postpone this until we have a proper solution for how we want to handle styles in the data browser in general.

**Comment by Vinnl** [comment]
I'd postpone this to be part of the UX work we should incorporate in our planning process later; the current data browser doesn't have a clear information hierarchy anyway.

**Comment by Vinnl** [comment]
Btw, quick fix might be: https://necolas.github.io/normalize.css/

**Comment by Vinnl** [comment]
Fixed by #68.
