### ISSUE TITLE
The non-minified mashlib.js must not be minified anywhere

### ISSUE THREAD

**Issue by timbl** [solid/mashlib#76]
Currently there are very long lines of minified code  in what should be debuggable un-minified code.  This makes debugging mashlib impossible.
```
$ line-length node_modules/solid-panes/dist/main.js
327476
```
Note also
```
$ line-length node_modules/solid-panes/dist/main.js
327476
```
where
``` 
`alias line-length='awk '\'' { if ( length > L ) { L=length} }END{ print L}'\'' '
```

**Comment by Vinnl** [comment]
Hmm, Mashlib itself seems to be unminified just fine here - it's solid-panes and solid-ui that are minified. This has been the case for a while for solid-panes, as far as I can see, but solid-ui is new.

I've created issues there:

- https://github.com/solid/solid-ui/issues/149
- https://github.com/solid/solid-panes/issues/191

One thing I did find, however, is that we're not producing a non-minified version of mashlib at all during the production build. It just happens to be packaged along if the person doing the publishing has already created it during development, but it might be outdated. Thus, I suppose this Issue can be used to fix that.

**Comment by Vinnl** [comment]
Ah, done some more digging: solid-ui is actually included both minified and unminified. The latter is likely the case due to it being included with solid-panes in its minified build. (So that does mean that this is not a new issue?)

**Comment by timbl** [comment]
This is not a ne issue, now, it has been a problem for a while.   Since lerna and mashlib-dev has been used, I suspect.  The whole process of creating a library in solid panes instead of building the mashlib from the node_modules tree has been a problem, as there have not been attempts to make non-minified versions of solid-panes.  I don't know whether with lerna it is possible to build  mashlib in the old way, using webpack to pull in the original sources.  It is certainly made trickier by using typescript.

**Comment by Vinnl** [comment]
This was fixed in https://github.com/solid/solid-panes/commit/49de3b94bf4d099cd3036d300a3e0fc24e44a9ba.
