### ISSUE TITLE
solid-ui share pane broken in mashlib 1.0.6 

### ISSUE THREAD

**Issue by bourgeoa** [solid/mashlib#78]
NSS 5.2.1 with mashlib 1.0.6
solid-ui share pane is broken : tried on https://bourgeoa.inrupt.net/public/

`acl-control.js:101 Uncaught (in promise) TypeError: Cannot read property 'http://www.w3.org/ns/auth/acl#Append
http://www.w3.org/ns/auth/acl#Control
http://www.w3.org/ns/auth/acl#Read
http://www.w3.org/ns/auth/acl#Write' of undefined
    at b (acl-control.js:101)
    at acl-control.js:1128
    at acl.js:423
    at acl.js:453
    at fetcher.js:938`

At first it seems that `acl-control.js` is not in line between `solid/solid-ui` and `mashlib/node_modules`

**Comment by Vinnl** [comment]
Two duplicates:

- https://github.com/solid/solid-panes/issues/193
- https://github.com/solid/solid-panes/issues/194

The issue is probably in solid-ui, see https://github.com/solid/solid-panes/issues/193#issuecomment-549777549 for more analysis.

**Comment by bourgeoa** [comment]
closed with https://github.com/solid/solid-ui/pull/153
integrated in mashlib 1.1.7
