### ISSUE TITLE
Notepad collaboration

### ISSUE THREAD

**Issue by SharonStrats** [solid/mashlib#90]
I am under the impression that more than one person can contribute to a particular notepad - pad.ttl document.  I wanted to confirm if this is the case?  And if this is the case, how should the process flow work?

I tried to make this happen by:
1) created a notepad document under my WebID
2) Added a triple (by entering text in input field provided)
3) Gave full access to another test user
4) Logged in as the test user and accessed the document
5) Added more triples (again by entering text in input field provided)
6) As the test user I was not shown as a participant, nor was the input box color changed to show another user
**(I was able to add to this document, but it appeared as if it was modified by the original creator)**

**Comment by SharonStrats** [comment]
In researching further I see that the particular user I was using example-user shows a 403 error in the console when I am logged in as example-user on the document created by sharonstrats.  I am wondering if this is preventing it to show.

**Comment by jeff-zucker** [comment]
@SharonStrats 403 means the app is not trusted rather than 401 which is user is not authorized.  So in the profile of the user, set the domain of the app as trusted.

**Comment by SharonStrats** [comment]
awww thank you!  I will try to set this.

**Comment by SharonStrats** [comment]
This particular user is still a problem for me, however I believe it has something to do with my cache.  I have had another user from their computer add another line (triple) to this document.  When I open the notepad again I can see his triple and his name in participation as well as a different color scheme. I am closing this issue.
